### ISSUE TITLE
pcl_catkin old version

### ISSUE THREAD

**Issue by robust-lu** [ethz-asl/pcl_catkin#18]
Hi, pcl_catkin1.9 needs C++14 or above, but my compiler only C++11. so where can i get the old version of pcl_catkin for convient? thanks

**Comment by mmiles19** [comment]
I get the following error in ~/catkin_ws/devel/.private/pcl_catkin/include/pcl-1.9/pcl/pcl_config.h:9:4: 
`error: #error PCL requires C++14 or above`.
I have C++14 installed and have successfully compiled/tested with it.

**Comment by margaritaG** [comment]
@robust-lu tracing back through the commits on master one ends up at this version: https://github.com/ethz-asl/pcl_catkin/tree/69e49f3188b7bcc8f7487564b0af10376c095d0b where the pcl version to checkout was set to tag `pcl-1.8.0`.

If 1.8.0 works for you, you could give it a try. However, I imagine all sorts of compiling and/or runtime issues could arise since that is a veeery old commit.
